permalink: /:categories/:title/

markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

highlighter: pygments

site_url: http://www.miguelmota.com

site_name: Miguel Mota | Web Developer

google_analytics_uid: UA-12642068-1

disqus_shortname: miguelmota

theme:

  homepage_featured: 1

  homepage_posts: 100

  featured_wordcount: 70

port: 9999

exclude: [config, README.md, Rakefile, package.json, LICENSE.md, gruntfile.js, Gemfile, Gemfile.lock, sass_config.rb, component.json, node_modules, vendor, .travis.yml, .project, .gitignore, .gitattributes, .editorconfig, CNAME]

compress_html:
  clippings: []
  comments: ["<!-- ", " -->"]
  endings: []
  profile: false
  ignore:
    envs: []
